copy.sh: Fix script for Gentoo
Gentoo requires the use of `--user` for pip installations to avoid breaking `python-exec`:

ERROR: (Gentoo) Please run pip with the --user option to avoid breaking python-exec